# Generated by Django 5.1 on 2026-04-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("multa_atraso", models.FloatField()),
                ("valor_mensal", models.FloatField()),
                ("valor_promocao", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Digite seu nome completo", max_length=50
                    ),
                ),
                ("email", models.EmailField(max_length=100)),
                ("cpf", models.CharField(max_length=11, unique=True)),
                ("telefone", models.CharField(max_length=15)),
                ("codigo", models.CharField(max_length=30, verbose_name="código")),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("cadastrado_em", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Fornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Digite seu nome completo", max_length=50
                    ),
                ),
                ("cnpj", models.CharField(max_length=50)),
                ("contato", models.CharField(max_length=50)),
                ("endereco", models.CharField(max_length=100, verbose_name="endereço")),
                (
                    "tipo_distribuicao",
                    models.CharField(
                        max_length=50, verbose_name="tipo de distribuição"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Genero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
            ],
        ),
    ]
