# Generated by Django 5.1 on 2026-04-30 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locadora", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="cpf",
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.CreateModel(
            name="Filme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        help_text="Digite o titulo do filme",
                        max_length=50,
                        verbose_name="Título",
                    ),
                ),
                (
                    "duração",
                    models.CharField(
                        help_text="Digite a duração do filme",
                        max_length=10,
                        verbose_name="Duração",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=10, verbose_name="Descrição"),
                ),
                (
                    "classificacao",
                    models.CharField(max_length=2, verbose_name="Classificação"),
                ),
                (
                    "prazo_devolucao",
                    models.IntegerField(
                        help_text="Prazo em dias",
                        max_length=4,
                        verbose_name="Prazo de devolução",
                    ),
                ),
                (
                    "ano_lancamento",
                    models.IntegerField(max_length=4, verbose_name="Ano de lançamento"),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="locadora.categoria",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Locacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_locacao", models.DateField(auto_now_add=True)),
                ("data_devolucao", models.DateField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="locadora.cliente",
                    ),
                ),
                (
                    "filme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="locadora.filme"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Multa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.FloatField(verbose_name="Valor")),
                ("dias_atraso", models.IntegerField(verbose_name="Dias de Atraso")),
                ("paga", models.BooleanField(default=False, verbose_name="Paga")),
                (
                    "data_gerada",
                    models.DateTimeField(auto_now_add=True, verbose_name="Data Gerada"),
                ),
                (
                    "locacao",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="multa",
                        to="locadora.locacao",
                        verbose_name="Locação",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor_pago", models.FloatField(verbose_name="Valor Pago")),
                (
                    "data_pagamento",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data do Pagamento"
                    ),
                ),
                (
                    "metodo_pagamento",
                    models.CharField(max_length=50, verbose_name="Método de Pagamento"),
                ),
                (
                    "comprovante_gerado",
                    models.BooleanField(
                        default=False, verbose_name="Comprovante Gerado"
                    ),
                ),
                (
                    "locacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagamentos",
                        to="locadora.locacao",
                        verbose_name="Locação",
                    ),
                ),
            ],
        ),
    ]
