# Generated by Django 5.1 on 2026-05-14 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locadora", "0002_alter_cliente_cpf_filme_locacao_multa_pagamento"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pagamento",
            name="locacao",
        ),
        migrations.RenameField(
            model_name="genero",
            old_name="tipo",
            new_name="nome",
        ),
        migrations.RemoveField(
            model_name="categoria",
            name="multa_atraso",
        ),
        migrations.RemoveField(
            model_name="categoria",
            name="valor_mensal",
        ),
        migrations.RemoveField(
            model_name="categoria",
            name="valor_promocao",
        ),
        migrations.RemoveField(
            model_name="filme",
            name="prazo_devolucao",
        ),
        migrations.RemoveField(
            model_name="genero",
            name="descricao",
        ),
        migrations.AddField(
            model_name="categoria",
            name="nome",
            field=models.CharField(default="nome", max_length=100, verbose_name="nome"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="categoria",
            name="prazo_devolucao",
            field=models.IntegerField(
                default=30, help_text="Prazo em dias", verbose_name="Prazo de devolução"
            ),
        ),
        migrations.AddField(
            model_name="categoria",
            name="preco",
            field=models.DecimalField(
                decimal_places=2, default=100, max_digits=6, verbose_name="preço"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="filme",
            name="genero",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.PROTECT,
                to="locadora.genero",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="locacao",
            name="data_pagamento",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data do Pagamento"
            ),
        ),
        migrations.AddField(
            model_name="locacao",
            name="metodo_pagamento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PIX", "PIX"),
                    ("CC", "Cartão de crédito"),
                    ("débito", "Débito"),
                    ("boleto", " Boletos Bancários"),
                    ("carteira digital", "e-wallets"),
                ],
                max_length=50,
                null=True,
                verbose_name="Método de Pagamento",
            ),
        ),
        migrations.AddField(
            model_name="locacao",
            name="valor",
            field=models.DecimalField(
                decimal_places=2, default=100, max_digits=6, verbose_name="preço"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="locacao",
            name="valor_pago",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=6, verbose_name="preço"
            ),
        ),
        migrations.AlterField(
            model_name="filme",
            name="ano_lancamento",
            field=models.IntegerField(verbose_name="Ano de lançamento"),
        ),
        migrations.AlterField(
            model_name="filme",
            name="classificacao",
            field=models.CharField(
                choices=[
                    ("L", "Livre"),
                    ("A10", "10 anos"),
                    ("A12", "12 anos"),
                    ("A14", "14 anos"),
                    ("A16", "16 anos"),
                    ("A18", "18 anos"),
                ],
                verbose_name="Classificação",
            ),
        ),
        migrations.AlterField(
            model_name="locacao",
            name="data_devolucao",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="locacao",
            name="data_locacao",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name="Multa",
        ),
        migrations.DeleteModel(
            name="Pagamento",
        ),
    ]
