# Generated by Django 5.1 on 2026-06-11 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locadora", "0004_categoria_atualizado_em_categoria_cadastrado_em_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fornecedor",
            options={"ordering": ["-id"]},
        ),
    ]
